language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t krobson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krobson/docker-react npm run test -- --coverage