FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
COPY package-lock.json .

RUN npm config set unsafe-prm true
RUN npm install

COPY . .

RUN chown -R node:node /app/node_modules

USER node

CMD ["npm", "run", "start"]